on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ env.python_version }}
      - name: Lint with Pre-commit
        uses: pre-commit/action@v2.0.3

  build:
    needs: lint
    name: build GTK binaries with gvsbuild
    runs-on: windows-latest
    timeout-minutes: 60
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.10'

      - name: Install visual studio tools
        run: choco install visualstudio2022-workload-vctools

      # Temporarily move the preinstalled git, it causes errors related to cygwin.
      - name: Move git binary
        run: move "C:\Program Files\Git\usr\bin" "C:\Program Files\Git\usr\notbin"
        shell: cmd

      - name: Build
        run: >
          python .\build.py build -p=x64 --vs-ver=17 --msys-dir=C:\msys64 --enable-gi
          --py-wheel --gtk3-ver=3.24 gtk3 graphene gobject-introspection pycairo
          pygobject adwaita-icon-theme hicolor-icon-theme gtksourceview4

      - name: Copy wheels to the build directory
        if: steps.cache.outputs.cache-hit != 'true'
        run: Get-ChildItem C:\gtk-build\build\x64\release\*\dist\*.whl | ForEach-Object -process { cp $_ C:\gtk-build\gtk\x64\release\ }

      - name: Restore git binary
        run: move "C:\Program Files\Git\usr\notbin" "C:\Program Files\Git\usr\bin"
        shell: cmd
